version: '3.7'
services:
  main:
    container_name: b4
    build:
      context: src/b4
      target: development
    volumes:
      - ./src/b4:/usr/src/app
      - /usr/src/app/node_modules #docker-compose up --build -V to rebuid if install any packages
    ports:
      - ${B4_PORT}:${B4_PORT}
      - "3100:3100"
    command: npm run start:dev
    env_file:
      - .env
    networks:
      nodejs:
        aliases:
            - nest
    depends_on:
      - elasticsearch
  elasticsearch:
      build:
        context: elasticsearch/
      volumes:
        - ./elasticsearch/config/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml:ro
      ports:
        - ${EL_PORT}:${EL_PORT}
        - "9300:9300"
      env_file:
        - .env
      environment:
        ES_JAVA_OPTS: "-Xmx256m -Xms256m"
      networks:
        nodejs:
          aliases:
            - elsearch

networks:
  nodejs:
    external: true